# Generated by Django 3.2.4 on 2021-09-14 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_friendly', models.BooleanField()),
                ('cat_friendly', models.BooleanField()),
                ('smoking_allowed', models.BooleanField()),
                ('additional_r', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet', models.BooleanField()),
                ('breakfast', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('additional_s', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('availability', models.BooleanField(null=True)),
                ('listed_date', models.DateField(max_length=20, null=True)),
                ('image1', models.FileField(upload_to='static/uploads')),
                ('image2', models.FileField(upload_to='static/uploads')),
                ('image3', models.FileField(upload_to='static/uploads')),
                ('image4', models.FileField(upload_to='static/uploads')),
                ('image5', models.FileField(upload_to='static/uploads')),
                ('image6', models.FileField(upload_to='static/uploads')),
                ('rating', models.IntegerField(null=True)),
                ('rules', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.rules')),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.services')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
