# Generated by Django 3.2.4 on 2021-09-15 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='price',
        ),
    ]
