# Generated by Django 3.2.4 on 2021-09-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='adults',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='child',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
