# Generated by Django 3.2.4 on 2021-09-22 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20210922_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='adults',
        ),
        migrations.RemoveField(
            model_name='package',
            name='child',
        ),
        migrations.AddField(
            model_name='package',
            name='type_of_stay',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
