# Generated by Django 3.2.4 on 2021-08-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_id_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/users/default.jpg', null=True, upload_to='static/users'),
        ),
    ]
