# Generated by Django 3.2.4 on 2021-08-09 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='availability',
            field=models.BooleanField(null=True),
        ),
    ]
