# Generated by Django 3.2.4 on 2021-08-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0003_hostel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='services',
            field=models.CharField(max_length=50),
        ),
    ]
