# Generated by Django 3.2.4 on 2021-08-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0004_alter_hostel_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='services',
            field=models.CharField(max_length=1000),
        ),
    ]
