# Generated by Django 3.2.4 on 2021-08-10 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0005_alter_hostel_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='services',
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet', models.BooleanField()),
                ('breakfast', models.BooleanField()),
                ('gym', models.BooleanField()),
                ('gayser', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('hostel_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel')),
            ],
        ),
    ]
