# Generated by Django 3.2.4 on 2021-08-10 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0006_auto_20210810_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='additional_s',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_friendly', models.BooleanField()),
                ('cat_friendly', models.BooleanField()),
                ('additional_r', models.CharField(max_length=1000)),
                ('hostel_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel')),
            ],
        ),
    ]
