# Generated by Django 3.2.4 on 2021-08-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0007_auto_20210810_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='gayser',
            new_name='geyser',
        ),
    ]
