# Generated by Django 3.2.4 on 2021-08-11 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0015_alter_hostel_listed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='listed_date',
        ),
    ]
