# Generated by Django 3.2.4 on 2021-08-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0016_remove_hostel_listed_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='listed_date',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
