# Generated by Django 3.2.4 on 2021-08-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0020_alter_hostel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='additional_r',
            field=models.TextField(max_length=1000),
        ),
    ]
