# Generated by Django 3.2.4 on 2021-08-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0021_alter_rules_additional_r'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='additional_s',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
