# Generated by Django 3.2.4 on 2021-08-18 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0022_alter_services_additional_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='hostel_r',
        ),
        migrations.AddField(
            model_name='hostel',
            name='rules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostels.rules'),
        ),
    ]
