# Generated by Django 3.2.4 on 2021-08-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0023_auto_20210818_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
