# Generated by Django 3.2.4 on 2021-08-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0024_hostel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
