# Generated by Django 3.2.4 on 2021-09-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0026_hostelbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelbooking',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hostelbooking',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
