# Generated by Django 3.2.4 on 2021-09-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0027_auto_20210907_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostelbooking',
            name='adult',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='hostelbooking',
            name='child',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
