# Generated by Django 3.2.4 on 2021-09-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0028_auto_20210907_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostelbooking',
            old_name='data',
            new_name='date',
        ),
    ]
