# Generated by Django 3.2.4 on 2021-08-28 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210821_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='comment',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ratings',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Replies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.TextField(max_length=1000, null=True)),
                ('date', models.DateField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ratings')),
            ],
        ),
    ]
