# Generated by Django 3.2.4 on 2021-08-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210828_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
