# Generated by Django 3.2.4 on 2021-08-28 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_replies_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='likes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
