# Generated by Django 3.2.4 on 2021-09-12 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20210912_1359'),
        ('home', '0006_replies_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house.home'),
        ),
    ]
