# Generated by Django 3.2.4 on 2021-09-12 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0031_alter_hostelbooking_date'),
        ('home', '0007_ratings_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel'),
        ),
    ]
