# Generated by Django 3.2.4 on 2021-09-18 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_hotels_price'),
        ('home', '0008_alter_ratings_hostel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotels'),
        ),
    ]
