# Generated by Django 3.2.4 on 2021-08-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_activity_id_activity_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='property_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
