# Generated by Django 3.2.4 on 2021-08-13 11:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_alter_chat_person_1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='ChatRoom',
        ),
    ]
