# Generated by Django 3.2.4 on 2021-08-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_chat_chatroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='person_2',
            field=models.IntegerField(),
        ),
    ]
