# Generated by Django 3.2.4 on 2021-08-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
