# Generated by Django 3.2.4 on 2021-08-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_message_sender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room_id',
            new_name='room',
        ),
    ]
