# Generated by Django 3.2.4 on 2021-08-15 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0019_services_laundry'),
        ('user', '0015_chatroom_reply_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='reply_on',
        ),
        migrations.AddField(
            model_name='message',
            name='reply_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel'),
        ),
    ]
