# Generated by Django 3.2.4 on 2021-08-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_address'),
        ('user', '0018_alter_chatroom_person_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='person_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
