# Generated by Django 3.2.4 on 2021-08-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_rename_person_1_chatroom_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='person',
            field=models.IntegerField(null=True),
        ),
    ]
