# Generated by Django 3.2.4 on 2021-09-03 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_address'),
        ('user', '0023_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notification_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
