# Generated by Django 3.2.4 on 2021-09-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_notifications_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='subject',
            new_name='subject_id',
        ),
    ]
