# Generated by Django 3.2.4 on 2021-09-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_rename_subject_notifications_subject_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='notifications',
            name='subject',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
