# Generated by Django 3.2.4 on 2021-09-12 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_auto_20210912_1359'),
        ('user', '0030_auto_20210910_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house.home'),
        ),
    ]
