# Generated by Django 3.2.4 on 2021-09-12 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0031_alter_hostelbooking_date'),
        ('user', '0031_activity_activity_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hostels.hostel'),
        ),
    ]
