# Generated by Django 3.2.4 on 2021-09-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_activity_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
