# Generated by Django 3.2.4 on 2021-09-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_notifications_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='Notification',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
