# Generated by Django 3.2.4 on 2021-09-12 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internet', models.BooleanField()),
                ('parking', models.BooleanField()),
                ('water', models.BooleanField()),
                ('additional_s', models.TextField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('price', models.IntegerField()),
                ('home_type', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('availability', models.BooleanField(null=True)),
                ('listed_date', models.DateField(max_length=20, null=True)),
                ('image1', models.FileField(upload_to='static/uploads')),
                ('image2', models.FileField(upload_to='static/uploads')),
                ('image3', models.FileField(upload_to='static/uploads')),
                ('image4', models.FileField(upload_to='static/uploads')),
                ('image5', models.FileField(upload_to='static/uploads')),
                ('image6', models.FileField(upload_to='static/uploads')),
                ('rating', models.IntegerField(null=True)),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house.services')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
