# Generated by Django 3.2.4 on 2021-09-12 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_friendly', models.BooleanField()),
                ('cat_friendly', models.BooleanField()),
                ('smoking_allowed', models.BooleanField()),
                ('additional_r', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='home',
            name='rules',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='house.rules'),
        ),
    ]
