# Generated by Django 3.2.4 on 2021-09-13 05:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_homerenting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homerenting',
            name='member',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
