# Generated by Django 3.2.4 on 2021-09-13 05:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20210913_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homerenting',
            name='duration',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)]),
        ),
    ]
